const config = window.APP_CONFIG;
const API_BASE = config.apiBase;
const $ = (id) => document.getElementById(id);
const state = { token: null, user: null, watchId: null, lastSampleAt: 0, logs: [] };

function toast(message) { const element = $("toast"); element.textContent = message; element.style.display = "block"; setTimeout(() => { element.style.display = "none"; }, 3200); }
function formatDateYMD(date = new Date()) { return date.toISOString().slice(0, 10); }
function formatDateTime(timestamp) { return timestamp ? new Date(timestamp).toLocaleString("ar-EG", { dateStyle: "short", timeStyle: "short" }) : "—"; }
function formatDuration(seconds) { if (seconds == null) return "—"; return `${Math.floor(seconds / 3600)}h ${Math.floor((seconds % 3600) / 60)}m`; }
async function api(path, options = {}) { const response = await fetch(`${API_BASE}${path}`, { ...options, headers: { "Content-Type": "application/json", ...(state.token ? { Authorization: `Bearer ${state.token}` } : {}), ...(options.headers || {}) } }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "حدث خطأ في الخادم"); return result; }
function showView(view) { $("viewAuth").style.display = view === "auth" ? "block" : "none"; $("viewEmployee").style.display = view === "employee" ? "block" : "none"; $("viewAdmin").style.display = view === "admin" ? "block" : "none"; $("btnLogout").style.display = view === "auth" ? "none" : "inline-flex"; }
function positionOnce() { return new Promise((resolve, reject) => { if (!navigator.geolocation) return reject(new Error("Geolocation غير مدعوم.")); navigator.geolocation.getCurrentPosition(resolve, () => reject(new Error("تعذر الحصول على الموقع.")), { enableHighAccuracy: true, timeout: 15000, maximumAge: 0 }); }); }
function stopMovementWatch() { if (state.watchId != null) navigator.geolocation.clearWatch(state.watchId); state.watchId = null; }
function startMovementWatch() { stopMovementWatch(); state.watchId = navigator.geolocation.watchPosition(async (position) => { const now = Date.now(); if (now - state.lastSampleAt < config.movementSampleEveryMs) return; state.lastSampleAt = now; try { const result = await api("/api/attendance/movement", { method: "POST", body: JSON.stringify({ lat: position.coords.latitude, lng: position.coords.longitude, accuracy: position.coords.accuracy }) }); $("geoStatus").textContent = `مراقبة الحركة... المسافة ~ ${Math.round(result.distance)}m`; } catch (_) {} }, () => { $("geoStatus").textContent = "تعذر تحديث مراقبة الحركة."; }, { enableHighAccuracy: true, maximumAge: 0 }); }
async function refreshEmployee() { const result = await api("/api/attendance/me"); state.logs = result.logs || []; const today = state.logs.find((log) => log.date === formatDateYMD()); $("empName").textContent = state.user.username; $("todayStr").textContent = formatDateYMD(); $("outCheckIn").textContent = formatDateTime(today?.check_in_time); $("outCheckOut").textContent = formatDateTime(today?.check_out_time); $("outWork").textContent = formatDuration(today?.work_seconds); $("outFlags").textContent = today?.flags?.length ? today.flags.join(", ") : "—"; $("btnCheckIn").disabled = Boolean(today); $("btnCheckOut").disabled = !today || Boolean(today.check_out_time); $("logsTable").querySelector("tbody").innerHTML = state.logs.map((log) => `<tr><td>${log.date}</td><td>${formatDateTime(log.check_in_time)}</td><td>${formatDateTime(log.check_out_time)}</td><td>${formatDuration(log.work_seconds)}</td><td>${log.flags?.length ? log.flags.join(", ") : "—"}</td></tr>`).join(""); if (today && !today.check_out_time) startMovementWatch(); }
async function refreshAdmin() { const result = await api("/api/admin/logs"); const logs = result.logs || []; $("adminOffice").textContent = `${config.office.lat}, ${config.office.lng}`; $("adminRadius").textContent = `${config.geofenceRadiusMeters} متر`; $("adminTable").querySelector("tbody").innerHTML = logs.map((log) => `<tr><td>${log.username}</td><td>${log.date}</td><td>${formatDateTime(log.check_in_time)}</td><td>${formatDateTime(log.check_out_time)}</td><td>${formatDuration(log.work_seconds)}</td><td>${log.flags?.length ? log.flags.join(", ") : "—"}</td></tr>`).join("") || '<tr><td colspan="6">لا توجد سجلات بعد.</td></tr>'; return logs; }
function makeExcel(rows, sheetName) { const headers = Object.keys(rows[0] || { username: "", date: "", checkIn: "", checkOut: "", workHours: "", flags: "" }); const csv = [headers, ...rows.map((row) => headers.map((header) => row[header] ?? ""))].map((row) => row.map((value) => `"${String(value).replaceAll('"', '""')}"`).join(",")).join("\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); link.download = `${sheetName.toLowerCase()}_${formatDateYMD()}.csv`; link.click(); URL.revokeObjectURL(link.href); }
function exportLogs(logs, sheetName) { makeExcel(logs.map((log) => ({ username: log.username, date: log.date, checkIn: formatDateTime(log.check_in_time), checkOut: formatDateTime(log.check_out_time), workHours: log.work_seconds == null ? "" : (log.work_seconds / 3600).toFixed(2), flags: log.flags?.join(", ") || "" })), sheetName); }
function showAuthRole() { $("adminPasswordField").style.display = $("role").value === "admin" ? "block" : "none"; }

$("role").addEventListener("change", showAuthRole);
$("btnLogin").addEventListener("click", async () => { try { const role = $("role").value; const username = $("username").value.trim(); const result = await api("/api/auth/login", { method: "POST", body: JSON.stringify({ role, username, password: $("adminPassword").value }) }); state.token = result.token; state.user = result.user; toast(role === "admin" ? "تم دخول Admin ✅" : "تم دخول الموظف ✅"); if (role === "admin") { showView("admin"); await refreshAdmin(); } else { showView("employee"); await refreshEmployee(); } } catch (error) { toast(error.message); } });
$("btnCheckIn").addEventListener("click", async () => { try { $("btnCheckIn").disabled = true; $("geoStatus").textContent = "جاري التحقق من الموقع..."; const position = await positionOnce(); await api("/api/attendance/check-in", { method: "POST", body: JSON.stringify({ lat: position.coords.latitude, lng: position.coords.longitude, accuracy: position.coords.accuracy }) }); $("geoStatus").textContent = "تم Check-in والتحقق من الموقع ✅"; await refreshEmployee(); } catch (error) { toast(error.message); $("btnCheckIn").disabled = false; } });
$("btnCheckOut").addEventListener("click", async () => { try { $("btnCheckOut").disabled = true; await api("/api/attendance/check-out", { method: "POST", body: "{}" }); stopMovementWatch(); $("geoStatus").textContent = "تم Check-out بدون اشتراط الموقع ✅"; await refreshEmployee(); } catch (error) { toast(error.message); $("btnCheckOut").disabled = false; } });
$("btnLogout").addEventListener("click", () => { stopMovementWatch(); state.token = null; state.user = null; state.logs = []; showView("auth"); });
$("btnExportExcel").addEventListener("click", () => exportLogs(state.logs, "MyAttendance"));
$("btnAdminExportExcel").addEventListener("click", async () => { try { exportLogs(await refreshAdmin(), "AllAttendance"); } catch (error) { toast(error.message); } });
$("btnClearMyData").addEventListener("click", async () => { if (!confirm("متأكد؟ سيتم حذف سجلاتك من قاعدة البيانات.")) return; await api("/api/attendance/my", { method: "DELETE" }); await refreshEmployee(); });
$("btnAdminClearAll").addEventListener("click", async () => { if (!confirm("متأكد؟ سيتم حذف كل السجلات من قاعدة البيانات.")) return; await api("/api/admin/logs", { method: "DELETE" }); await refreshAdmin(); });
$("geoStatus").textContent = `Geofence: ${config.geofenceRadiusMeters}m حول المكتب | حد دقة GPS: ${config.maxGpsAccuracyMeters}m`;
showAuthRole();
